/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LegislationRouteImport } from './routes/legislation'
import { Route as FxTrendsRouteImport } from './routes/fx-trends'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthConnectRouteImport } from './routes/auth_.connect'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'

const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislationRoute = LegislationRouteImport.update({
  id: '/legislation',
  path: '/legislation',
  getParentRoute: () => rootRouteImport,
} as any)
const FxTrendsRoute = FxTrendsRouteImport.update({
  id: '/fx-trends',
  path: '/fx-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnectRoute = AuthConnectRouteImport.update({
  id: '/auth_/connect',
  path: '/auth/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/fx-trends': typeof FxTrendsRoute
  '/legislation': typeof LegislationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tax': typeof TaxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/connect': typeof AuthConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/fx-trends': typeof FxTrendsRoute
  '/legislation': typeof LegislationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tax': typeof TaxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/connect': typeof AuthConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/fx-trends': typeof FxTrendsRoute
  '/legislation': typeof LegislationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tax': typeof TaxRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/auth_/connect': typeof AuthConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fx-trends'
    | '/legislation'
    | '/reports'
    | '/settings'
    | '/tax'
    | '/auth/callback'
    | '/auth/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fx-trends'
    | '/legislation'
    | '/reports'
    | '/settings'
    | '/tax'
    | '/auth/callback'
    | '/auth/connect'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fx-trends'
    | '/legislation'
    | '/reports'
    | '/settings'
    | '/tax'
    | '/auth_/callback'
    | '/auth_/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  FxTrendsRoute: typeof FxTrendsRoute
  LegislationRoute: typeof LegislationRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TaxRoute: typeof TaxRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConnectRoute: typeof AuthConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislation': {
      id: '/legislation'
      path: '/legislation'
      fullPath: '/legislation'
      preLoaderRoute: typeof LegislationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx-trends': {
      id: '/fx-trends'
      path: '/fx-trends'
      fullPath: '/fx-trends'
      preLoaderRoute: typeof FxTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/connect': {
      id: '/auth_/connect'
      path: '/auth/connect'
      fullPath: '/auth/connect'
      preLoaderRoute: typeof AuthConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  FxTrendsRoute: FxTrendsRoute,
  LegislationRoute: LegislationRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TaxRoute: TaxRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConnectRoute: AuthConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
